sudo: false
language: groovy
jdk:
- oraclejdk8
before_script:
- rm -rf target
- npm install -g bower
script: "./travis.sh"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.grails/wrapper
  - $HOME/.m2
  - $HOME/.bower/cache
